-- MySQL Script generated by MySQL Workbench
-- 08/20/17 18:20:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report` (
  `rep_Code` INT NOT NULL,
  `rep_Date` DATE NULL,
  PRIMARY KEY (`rep_Code`),
  UNIQUE INDEX `rep_Code_UNIQUE` (`rep_Code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Website`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Website` (
  `web_Code` INT NOT NULL,
  `web_Name` VARCHAR(45) NULL,
  `web_Url` VARCHAR(45) NULL,
  PRIMARY KEY (`web_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `rev_Code` INT NOT NULL,
  `rev_Title` VARCHAR(45) NULL,
  `rev_Comment` VARCHAR(45) NULL,
  `rec_Rating` VARCHAR(45) NULL,
  `rev_Date` DATE NULL,
  `Website_web_Code` INT NOT NULL,
  PRIMARY KEY (`rev_Code`),
  UNIQUE INDEX `rev_Code_UNIQUE` (`rev_Code` ASC),
  INDEX `fk_Review_Website1_idx` (`Website_web_Code` ASC),
  CONSTRAINT `fk_Review_Website1`
    FOREIGN KEY (`Website_web_Code`)
    REFERENCES `mydb`.`Website` (`web_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sentiments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sentiments` (
  `positive` BINARY NULL,
  `negative` BINARY NULL,
  `rep_Code` INT NOT NULL,
  `rev_Code` INT NOT NULL,
  INDEX `rep_Code_idx` (`rep_Code` ASC),
  INDEX `rev_Code_idx` (`rev_Code` ASC),
  CONSTRAINT `rep_Code`
    FOREIGN KEY (`rep_Code`)
    REFERENCES `mydb`.`Report` (`rep_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rev_Code`
    FOREIGN KEY (`rev_Code`)
    REFERENCES `mydb`.`Review` (`rev_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
